name: "AntiGravity"
version: "0.1.1"
slug: "antigravity"
description: "VS Code with Gemini AI for Home Assistant."
url: "https://github.com/Iron-Matrix4/antigravity-addon"
startup: application
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
map:
  - config:rw
options:
  password: ""
  api_key: ""
schema:
  password: str
  api_key: str
ports:
  8080/tcp: 8080
webui: "http://[HOST]:[PORT:8080]"

