name: "AntiGravity"
version: "0.0.2"
slug: "antigravity"
description: "The AntiGravity Agent for Home Assistant."
url: "https://github.com/home-assistant/addons"
startup: application
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
map:
  - config:rw
options:
  api_key: ""
schema:
  api_key: str
ports:
  8099/tcp: 8099
webui: "http://[HOST]:[PORT:8099]"
